### PR TITLE
Fix version reference

### PR DESCRIPTION
**Pull request by WtfJoke**
**What**:
Fixing reference to old version in README of gh-pages

**Why**:
We shouldnt reference to specific versions (or in this case old versions)

**How**:
Replaced old version 2.0.1 with X.X.X

**Checklist**:

- [ ] Documentation added
N/A
- [ ] Changelog updated
N/A
- [ ] Tests added
N/A
      
- [x] Ready to be merged

### CODE REVIEW

**Comment by maiksensi** [comment]
Hey @WtfJoke can you explain a bit, what does improves? It seems to me the change is rather confusing if users copy & paste the `pom` entry. I would either always use the newest version here or add a note that X.X.X needs to be substituted for the newest CM version.

What do you think?

**Comment by WtfJoke** [comment]
It improves that no old chaosmonkey will be used, just by copy pasting from Readme. 

We have that X.X.X reference already in the same file (see https://github.com/codecentric/chaos-monkey-spring-boot/blob/gh-pages/README.md#dependency-in-your-pom). So this PR brings consistency. 


We could change both X.X.X references to current version, but its easy to miss on each release (unless we have a release checklist).  I would preferr to do that (note is ok as well, but is polluting the readme unnecessary)

**Comment by maiksensi** [comment]
Fine then. Keep it like it is. Let's merge this after the bugfix release.

**Comment by WtfJoke** [comment]
Will create a new PR for chaning it to next release version (instead of X.X.X)

**Pull request closed without merging**
