### PR TITLE
rename integration tests

### PR DESCRIPTION
**Pull request by Glosur**
Follow [TestName]Integration, as JUnit5 allow for naming ending by
something else than test

**What**: #165 

**Why**: Harmonize test naming

**How**: Renamed specified tests

**Checklist**:

- [NA] Documentation added
      
- [NA] Changelog updated
      
- [NA] Tests added
      
- [X] Ready to be merged

### CODE REVIEW

**Comment by maiksensi** [comment]
Hey @Glosur,
thank you for your contribution ❤️  it is much appreciated. I'll review it today.

**Comment by Glosur** [comment]
Woops, thought I posted a message, but looks like I dondt click on send

Where should I add myself on the changelog ?

**Comment by WtfJoke** [comment]
Hi @Glosur 
No worries, I think your PR fits in category "Improvements" the best. Thank you :)

**Comment by maiksensi** [comment]
Hey @Glosur,
yeah what Manuel said, + the file is: https://github.com/codecentric/chaos-monkey-spring-boot/blob/master/chaos-monkey-docs/src/main/asciidoc/changes.adoc

**Comment by Glosur** [comment]
Should be OK now

**Pull request merged**
