### PR TITLE
Fix #118 by excluding spring.cloud.context in component watcher

### LINKED ISSUE #118: BeanCurrentlyInCreationException after upgrade to 2.1.0
After upgrading from 2.0.2 to 2.1.0 our Spring Boot applications will no longer start due to a BeanCurrentlyInCreationException.

## Expected Behavior
Spring Boot application should start.

## Current Behavior
Spring Boot application does not start.

## Possible Solution
Not sure. This only occurs when spring-cloud-starter-sleuth is also on the classpath.

## Steps to Reproduce
[demo.zip](https://github.com/codecentric/chaos-monkey-spring-boot/files/3589861/demo.zip)

## Context (Environment)
Automated upgrade of 3rd party library versions.

### PR DESCRIPTION
**Pull request by WtfJoke**
**What**:
Fixed Bug #118 

**Why**:
Projects which had dependencies to Spring Cloud were unable to start the container after using latest spring boot for chaos monkey (2.1.0)

**How**:
Excluded package `org.springframework.cloud.context.*` for beeing watched by ChaosMonkeyComponentWatcher (`de.codecentric.spring.boot.chaos.monkey.watcher.SpringComponentAspect`)

**Checklist**:

- [ ] Documentation added
N/A      
- [x] Changelog updated
      
- [ ] Tests added
      
- [x] Ready to be merged
      

Not sure how to test this in an automated way (we could add spring cloud context as a test dependency, so some tests would not boot).

Problem was that the `org.springframework.cloud.context.properties.ConfigurationPropertiesBeans` is also a Component and triggered `de.codecentric.spring.boot.chaos.monkey.watcher.SpringComponentAspect` which injected a ChaosMonkeyRequestScope and caused the issue.

Thanks and shoutout to @srempfer, @maiksensi, @Pinguwien and @t1, with your help it wouldnt have been possible to fix it 🙏

### CODE REVIEW

**Comment by ingoschaal** [comment]
@WtfJoke thanks, this fix works for me

**Comment by maiksensi** [comment]
@ingoschaal if you want to hack a bit more on chaos monkey, we're hosting a hackergarten next week :) link to the event - https://www.meetup.com/Hackergarten-Stuttgart/

**Comment by ingoschaal** [comment]
Hi Team,
when can we expect a 2.2.0 release. i would like to use this cool bugfix :-)

**Comment by maiksensi** [comment]
I think nothing speaks against it, so yes we can expect one this year. @WtfJoke do you want to todo it or should I?

**Comment by WtfJoke** [comment]
Probably I dont have any time this year (Releasing process is still something we weanted to improve 🙈  ). So I would be happy if you can do it. Or we can create a release together tomorrow 😄

**Comment by ingoschaal** [comment]
thank you thank you no stress. christmas is coming...

**Comment by WtfJoke** [comment]
@ingoschaal  Just figured out that, this bug fix is already included in our (now previous) release 2.1.1 see https://codecentric.github.io/chaos-monkey-spring-boot/2.1.1/#_bug_fixes

Neverthless @maiksensi just released 2.2.0 😄 🎉

**Comment by ingoschaal** [comment]
oh, I didn't know that, sorry :see_no_evil:
anyway many thanks to all  :smiley: :boom:

**Comment by merugu** [comment]
I'm still able to reproduce this issue after using chaos monkey 2.1.1 version and spring boot 2.1.10.RELEASE 

The below are the spring cloud dependencies i have 

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR4"
        mavenBom "org.springframework.cloud:spring-cloud-vault-dependencies:2.1.4.RELEASE"
    }
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-vault-dependencies:2.1.4.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-vault-config', version: '2.1.4.RELEASE'
   compile group: 'de.codecentric', name: 'chaos-monkey-spring-boot', version: '2.1.1'
    }
    
    Did I miss anything

**Pull request merged**
