### PR TITLE
Spring boot 1.5.x

### PR DESCRIPTION
**Pull request by wonwoo**
what do you think? 

#5 spring boot 1.5.x 

think about it.

### CODE REVIEW

**Comment by MrBW** [comment]
I´m not sure how to handle it...maybe we could support both. All new ideas and improvements can be supported by Chaos Monkey for Spring Boot 2.x. Let me think about it....because there are so many customers on Spring Boot 1.5.x...

What do you think, support both or not?

**Comment by MrBW** [comment]
Sounds great! How we should handle it? Should we start a branch for Spring Boot 1.5, because I want to attack more Components, which are only available in Spring Boot 2.

We could split our versions, followed by the Spring Boot version:
- chaos-monkey-spring-boot 1.0.x
- chaos-monkey-spring-boot 2.0.x

Any other ideas?

**Comment by tiarebalbi** [comment]
I think that's it, having two version will be a good way to keep up-to-date with the changes that are happening with spring 2.x and keep the old version working. 

The approach, I would go with the option of having a branch for 1.5 which will allow us to cherry-pick any of changes required or needed in that branch.

**Comment by MrBW** [comment]
Ok! Starting by 1.0.2 or maybe with 1.5.x for our Spring 1.5 support?

**Comment by tiarebalbi** [comment]
I would go 1.5.x.

**Comment by MrBW** [comment]
Ok, we will start a 1.5.x branch as soon as we have add some new features. We need to provide a dynamic configuration and metrics for both 1.5.x and 2.0.x. https://github.com/chaostoolkit would like to integrate the Chaos Monkey for Spring in there Chaos Engineering tool suite.

I will close this pr, because we can´t start at the moment and have to add the mentioned features.
Thanks for your PR and keep contributing, you are welcome! :-)

**Pull request closed without merging**
