### PR TITLE
Upgrade dependencies and upgrade to JUnit 5

### PR DESCRIPTION
**Pull request by WtfJoke**
**What**:
- Upgraded to latest dependencies as much as possible (Havent upgraded to Spring Boot 2.4.x yet, as no Spring Cloud Release is out yet)
- Upgraded all tests to JUnit 5 (removed references to JUnit 4 and JUnit 5 Vintage Engine)

**Why**:
- 🧹 To keep the monkey in shape 🐒 🏋️ 

**How**:
- Upgraded all tests and bumped the versions in various poms. 

**Checklist**:

- [ ] Documentation added **N/A**
      
- [x] Changelog updated
      
- [ ] Tests added **N/A**
      
- [x] Ready to be merged

### CODE REVIEW

**Comment by WtfJoke** [comment]
For some particular reason, this one version (2.3.6.RELEASE) of the Spring Boot Maven Plugin cannot be found in some maven central mirrors.

Allthough it exists in the official maven central https://search.maven.org/artifact/org.springframework.boot/spring-boot-maven-plugin/2.3.6.RELEASE/maven-plugin

But is not listed here: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-maven-plugin
Except when you use the direct link: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-maven-plugin/2.3.6.RELEASE

Travis seems to use a google mirror where its not present as well....
````
[ERROR] Plugin org.springframework.boot:spring-boot-maven-plugin:2.3.6.RELEASE or one of its dependencies could not be resolved: Could not find artifact org.springframework.boot:spring-boot-maven-plugin:jar:2.3.6.RELEASE in google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/) -> [Help 1]
````

**Comment by WtfJoke** [comment]
I reached out to the maintainers of the google maven central mirror by email.
https://storage-download.googleapis.com/maven-central/index.html

Lets see if I get an answer 😅

**Comment by WtfJoke** [comment]
Answer from Monday (03:00 UTC):
> I've verified that 2.3.6 is missing, but 2.4.0 is present.  I've also checked my upstream supplier and it's missing there -- I'll ask them to provide it.  (It usually takes them 24h or so)

So I keep waiting a bit more.

**Review by fletchgqc — COMMENTED** [review]
I find it fine, but there are some possible improvements:
a) Why do we include aspectJ, but use hamcrest matchers? We should remove the aspectj dependency. Alternatively switch to aspectj and remove hamcrest, but I would just do whatever is easier.
b) If you use Spring Boot 2.4+, you don't need to exclude the Junit Vintage dependencies, it's already like that by default. So I would recommend that.

**Comment by WtfJoke** [comment]
> Why do we include aspectJ, but use hamcrest matchers? We should remove the aspectj dependency. Alternatively switch to aspectj and remove hamcrest, but I would just do whatever is easier.

AspectJ is quite close to AssertJ (was confused at first) :D
I removed the assertJ dependency 🔥  (allthough I personally like it more, was less effort to remove it, so keep it for now). 


> If you use Spring Boot 2.4+, you don't need to exclude the Junit Vintage dependencies, it's already like that by default. So I would recommend that.

I keep it Spring Boot 2.3, will do a Chaos Monkey 2.3 Release and then upgrade to Spring Boot 2.4 afterwards in an additional PR. 


So that we somewhat keep to the [Support Page](https://codecentric.github.io/chaos-monkey-spring-boot/#support) which says:
> Chaos Monkey for Spring Boot versions will follow the versions of Spring Boot. The first number of the Chaos Monkey release will show you which is the right one for your Spring Boot version.

I'll probably need a reapproval @fletchgqc  😅

**Review by fletchgqc — APPROVED** [review]

**Pull request merged**
