### PR TITLE
Bumped up max level to 100 for scenarios requiring sub-10% chaos

### PR DESCRIPTION
**Pull request by mattk-pio**
This is a PR for issue #27 ; Tried to keep it as minimal and no-impact to anyone currently using the project. I think going forward it might feel a bit more intuitive to switch to percentages (where 100 is always, as opposed to 1), but it's not a big deal.

### CODE REVIEW

**Comment by MrBW** [comment]
Thx for your PR, I will come back on this...

**Comment by miklosbarabas** [comment]
@MrBW one question: shouldn't the `getTroubleRandom` method use the `level` field as the upper bound of the range of the pseudorandom being returned? Like:
`public int getTroubleRandom() {
        return RandomUtils.nextInt(1, level + 1);
}`

**Comment by deelthor** [comment]
@miklosbarabas interesting question. At least the behavior would be a bit different. imagine a level of 10. `RandomUtils.nextInt(1, level + 1)` will always return an int between 1 and 11. But the ChaosMonkey will only be executed when `chaosMonkeySettings.getAssaultProperties().getTroubleRandom() >= chaosMonkeySettings.getAssaultProperties().getLevel()`. So a level of 10 would mean a 10% chance, 100 a 1% chance etc., right? I am not sure whether this is the intended behavior. @MrBW has to decide.

**Comment by miklosbarabas** [comment]
@deelthor right, at least that is what I understood from the code. Btw the documentation is a bit misleading I think as it is stating: 
> How many requests are to be attacked. 1 each request, 5 each 5th request is attacked.
Which is not entirely true, it's more like what you said: a level of 10 means a 10% chance for the assault to happen (even previously before this MR). I might be mistaken tho.

**Pull request merged**
